jobs:
- name: self
  plan:
  - put: fly
    no_get: true
    params:
      options: |
        check-resource --resource ((pipeline))-self/code
  - in_parallel:
    - get: base
    - get: code
      params:
        depth: 1
  - load_var: matrix
    file: code/matrix.json
    format: json
  - task: fetch
    image: base
    config:
      platform: linux
      inputs:
      - name: code
      outputs:
      - name: code
      run:
        path: bash
        args:
        - -cx
        - |
          set -euo pipefail
          wget --no-cache https://raw.githubusercontent.com/encodeering/docker-ci/((.:matrix.concourse.dind))/modules/pipeline/docker.yml      -O code/matrix.yml
          wget --no-cache https://raw.githubusercontent.com/encodeering/docker-ci/((.:matrix.concourse.dind))/modules/pipeline/docker-hook.yml -O code/matrix-hook.yml
  - across:
    - var: pipeline
      values: ((.:matrix.pipelines))
    do:
    - set_pipeline: ((pipeline))
      file: code/matrix.yml
      vars:
        git:
          uri:      ((git.uri))
          branch:   ((git.branch))
        repository: ((repository))
        concourse:  ((.:matrix.concourse))
        platforms:  ((.:matrix.platforms))
        pipeline:   ((.:pipeline))
      instance_vars:
        base:       ((.:pipeline.base))
        variant:    ((.:pipeline.variant))
        version:    ((.:pipeline.version))
  - set_pipeline:   ((pipeline))-hook
    file: code/matrix-hook.yml
    vars:
      parent:       ((pipeline))
      pipelines:    ((.:matrix.pipelines))

resources:
- name: base
  type: registry-image
  source:
    repository: encodeering/alpine-amd64
    tag: 3.15
    registry_mirror:
      host:     ((docker.mirror))
      username: ((docker.username))
      password: ((docker.password))
- name: code
  type: git
  check_every: never
  source:
    uri:    ((git.uri))
    branch: ((git.branch))
- name: fly
  type: fly
  source:
    username: ((concourse.username))
    password: ((concourse.password))

resource_types:
- name: fly
  type: registry-image
  source:
    repository: elpaasoci/concourse-fly-resource
    tag: 2.0.2-orange-20240314
