jobs:
- name: build
  plan:
  - across:
    - var: pipeline
      values: ((pipelines))
      max_in_flight: 2
    do:
    - put: fly
      no_get: true
      params:
        options: |
          check-resource --resource ((parent))/base:"((.:pipeline.base))",variant:"((.:pipeline.variant))",version:"((.:pipeline.version))"/code
    - put: fly
      no_get: true
      params:
        options: |
          trigger-job --job ((parent))/base:"((.:pipeline.base))",variant:"((.:pipeline.variant))",version:"((.:pipeline.version))"/build --watch

resources:
- name: fly
  type: fly
  source:
    username: ((concourse.username))
    password: ((concourse.password))

resource_types:
- name: fly
  type: registry-image
  source:
    repository: elpaasoci/concourse-fly-resource
    tag: 2.0.2-orange-20240314
